{{- $clustername := .Metadata.Name }}
{{- range $addCompute := .Provider.Vsphere.ComputeNodes }}
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  {{- if eq $addCompute.Id 0 }}
  name: {{ $clustername }}-worker
  {{- else }}
  name: {{ $clustername }}-worker-{{ $addCompute.Id }}
  {{- end }}
  namespace: {{ $clustername }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  clusterDeploymentRef:
    name: {{ $clustername }}
  {{- if eq $addCompute.Id 0 }}
  name: worker
  {{- else }}
  name: worker-{{ $addCompute.Id }}
  {{- end }}
  platform:
    vsphere:
      cpus: {{ $addCompute.Cpus }}
      coresPerSocket: {{ $addCompute.CoresPerSocket }}
      memoryMB: {{ $addCompute.MemoryMB }}
      osDisk:
        diskSizeGB: {{ $addCompute.OsDiskSizeGB }}
      zones:
      {{- range $addCompute.Zones }}
      - '{{ . }}'
      {{- end }}
  replicas: {{ $addCompute.Replicas }}
{{- end }}