apiVersion: v1
kind: Secret
metadata:
  name: {{ .Metadata.Name }}-install-config
  namespace: {{ .Metadata.Name }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Metadata.Name }}
    baseDomain: {{ .Cluster.BaseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Provider.Vsphere.ControlNodes.Replicas }}
      platform:
        vsphere:
          cpus: {{ .Provider.Vsphere.ControlNodes.Cpus }}
          coresPerSocket: {{ .Provider.Vsphere.ControlNodes.CoresPerSocket }}
          memoryMB: {{ .Provider.Vsphere.ControlNodes.MemoryMB }}
          osDisk:
            diskSizeGB: {{ .Provider.Vsphere.ControlNodes.OsDiskSizeGB }}
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: {{ (index .Provider.Vsphere.ComputeNodes 0).Replicas }}
      platform:
        vsphere:
          cpus: {{ (index .Provider.Vsphere.ComputeNodes 0).Cpus }}
          coresPerSocket: {{ (index .Provider.Vsphere.ComputeNodes 0).CoresPerSocket }}
          memoryMB: {{ (index .Provider.Vsphere.ComputeNodes 0).MemoryMB }}
          osDisk:
            diskSizeGB: {{ (index .Provider.Vsphere.ComputeNodes 0).OsDiskSizeGB }}
    networking:
      networkType: {{ .Cluster.Networking.Type }}
      clusterNetwork:
      - cidr: {{ .Cluster.Networking.ClusterNetwork }}
        hostPrefix: {{ .Cluster.Networking.HostPrefix }}
      machineNetwork:
      - cidr: {{ .Cluster.Networking.MachineNetwork }}
      serviceNetwork:
      - {{ .Cluster.Networking.ServiceNetwork }}
    platform:
      vsphere:
        vCenter: {{ .Provider.Vsphere.Vcenter }}
        username: {{ .Provider.Vsphere.Username }}
        password: {{ .Provider.Vsphere.Password }}
        datacenter: {{ .Provider.Vsphere.Datacenter }}
        cluster: {{ .Provider.Vsphere.Cluster }}
        network: {{ .Provider.Vsphere.Network }}
        defaultDatastore: {{ .Provider.Vsphere.DefaultDatastore }}
        folder:  {{ .Provider.Vsphere.Folder }}
        apiVIP: {{ .Provider.Vsphere.ApiVIP }}
        ingressVIP: {{ .Provider.Vsphere.IngressVIP }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: {{ .Cluster.SshPubkey }}
