apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Metadata.Name }}
  namespace: {{ .Metadata.Name }}
  labels:
    cloud: 'Azure'
    region: {{ .Provider.Azure.Region }}
    vendor: OpenShift
  annotations:
    argocd.argoproj.io/sync-options: Delete=true
spec:
  powerState: {{ .Cluster.ClusterPowerState }}
  baseDomain: {{ .Cluster.BaseDomain }}
  clusterName: {{ .Metadata.Name }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    azure:
      baseDomainResourceGroupName: {{ .Provider.Azure.ResourceGroup }}
      credentialsSecretRef:
        name: {{ .Metadata.Name }}-azure-creds
      region: {{ .Provider.Azure.Region }}
      cloudName: AzurePublicCloud
  provisioning:
    installConfigSecretRef:
      name: {{ .Metadata.Name }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Metadata.Name }}-ssh-private-key
    imageSetRef:
      name: img{{ .Cluster.OcpVersionInstalled }}-multi-appsub
  pullSecretRef:
    name: {{ .Metadata.Name }}-pull-secret
