apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: {{ .Metadata.Name }}-cluster-version
  namespace: {{ .Metadata.Name }}
spec:
  clusterDeploymentRefs:
  - name: {{ .Metadata.Name }}

  patches:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    patch: |-
      {
      "spec": {
          "channel": "stable-{{ print "." (slice (split "." .Cluster.OcpVersion) 0 2) }}",
          "desiredUpdate": {
            "force": true,
            "version": "{{ .Cluster.OcpVersion }}"
          }
        }
      }
    patchType: merge
