apiVersion: v1
kind: Secret
metadata:
  name: {{ .Metadata.Name }}-install-config
  namespace: {{ .Metadata.Name }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Metadata.Name }}
    baseDomain: {{ .Cluster.BaseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Provider.Azure.ControlNodes.Replicas }}
      platform:
        azure:
          osDisk:
            diskSizeGB: {{ .Provider.Azure.ControlNodes.OsDiskSizeGB }}
          type: {{ .Provider.Azure.ControlNodes.Size }}
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: {{ (index .Provider.Azure.ComputeNodes 0).Replicas }}
      platform:
        azure:
          type: {{ (index .Provider.Azure.ComputeNodes 0).Size }}
          osDisk:
            diskSizeGB: {{ (index .Provider.Azure.ComputeNodes 0).OsDiskSizeGB }}
          zones:
          {{- range (index .Provider.Azure.ComputeNodes 0).Zones }}
          - '{{ . }}'
          {{- end }}
    networking:
      networkType: {{ .Cluster.Networking.Type }}
      clusterNetwork:
      - cidr: {{ .Cluster.Networking.ClusterNetwork }}
        hostPrefix: {{ .Cluster.Networking.HostPrefix }}
      machineNetwork:
      - cidr: {{ .Cluster.Networking.MachineNetwork }}
      serviceNetwork:
      - {{ .Cluster.Networking.ServiceNetwork }}
    platform:
      azure:
        baseDomainResourceGroupName: {{ .Provider.Azure.ResourceGroup }}
        cloudName: AzurePublicCloud
        region: {{ .Provider.Azure.Region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: {{ .Cluster.SshPubkey }}
